# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  # callbacks: 
  #   - class_path: lightning.pytorch.callbacks.ModelCheckpoint
  #     init_args:
  #       dirpath: checkpoints/visualbert/fhm
  #       monitor: hate_val_auroc
  #       mode: max
  #       save_top_k: 1
  #       every_n_epochs: 1
  #       save_last: True
  #   - class_path: lightning.pytorch.callbacks.EarlyStopping
  #     init_args:
  #       monitor: hate_val_auroc
  #       patience: 5
  #       mode: max
  #   - class_path: models.flava.MetricCallback
  #     init_args: 
  #       output_dict: {
  #         "hate ": 2
  #       }
model:
  class_path: models.visualbert.VisualBertClassificationModel
  init_args:
    model_class_or_path: uclanlp/visualbert-vqa-coco-pre
    cls_dict: {
      "hate": 2
    }
data:
  class_path: datamodules.VLFeaturesDataModule
  init_args:
    tokenizer_class_or_path: bert-base-uncased
    feats_dir: /mnt/sda/datasets/memes/fhm/features/unc-nlp/frcnn-vg-finetuned/
    annotation_filepaths: {
      train: /mnt/sda/datasets/memes/fhm_finegrained/annotations/train.jsonl,
      validate: /mnt/sda/datasets/memes/fhm_finegrained/annotations/dev_seen.jsonl,
      test: /mnt/sda/datasets/memes/fhm_finegrained/annotations/dev_seen.jsonl,
      predict: /mnt/sda/datasets/memes/fhm_finegrained/annotations/dev_seen.jsonl
    }
    shuffle_train: True
    batch_size: 32
    labels:
    - hate
