---
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: true
model:
  class_path: models.vlt5.VLT5ClassificationModel
  init_args:
    model_class_or_path: t5-base
    cls_dict:
      "label": 2
data:
  class_path: datamodules.VLFeaturesDataModule
  init_args:
    tokenizer_class_or_path: t5-base
    feats_dirs: {
      train: /mnt/sdb/aditi/datasets/fhm/features/unc-nlp/frcnn-vg-finetuned/,
      validate: /mnt/sdb/aditi/datasets/fhm/features/unc-nlp/frcnn-vg-finetuned/,
      test: /mnt/sdb/aditi/datasets/fhm/features/unc-nlp/frcnn-vg-finetuned/,
      predict: /mnt/sdb/aditi/datasets/fhm/features/unc-nlp/frcnn-vg-finetuned/
    }
    annotation_filepaths: {
      train: /mnt/sdb/aditi/hconvert/fhm/annotations/train.jsonl,
      validate: /mnt/sdb/aditi/hconvert/fhm/annotations/dev_seen.jsonl,
      test: /mnt/sdb/aditi/hconvert/fhm/annotations/dev_seen.jsonl,
      predict: /mnt/sdb/aditi/hconvert/fhm/annotations/dev_seen.jsonl
    }
    shuffle_train: true
    batch_size: 4
    labels:
      - label
