# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 2
  strategy: ddp_find_unused_parameters_true
  max_epochs: 50
  accumulate_grad_batches: 1
  enable_checkpointing: True
  limit_train_batches: 1
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/lxmert/fhm
        monitor: val_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_auroc
        patience: 5
        mode: max
    - class_path: models.lxmert.MetricCallback
      init_args: 
        output_dict: {
        "shaming": 2,
        "misogynous": 2,
        "objectification": 2,
        "violence": 2,
        "stereotype": 2
      }
model:
  class_path: models.lxmert.LxmertClassificationModel
  init_args:
    model_class_or_path: unc-nlp/lxmert-base-uncased
    output_dict: {
      "shaming": 2,
      "misogynous": 2,
      "objectification": 2,
      "violence": 2,
      "stereotype": 2
    }
data:
  class_path: datamodules.mami.MamiDataModule
  init_args:
    dataset_class: MamiDataset
    img_dir: {
      train: /mnt/sdb/aditi/MAMI/training/TRAINING/,
      validate: /mnt/sdb/aditi/MAMI/trial/Users/fersiniel/Desktop/MAMI - TO LABEL/TRIAL DATASET/,
      test: /mnt/sdb/aditi/MAMI/test/test/

    }
    annotation_filepaths: {
      train: /mnt/sdb/aditi/MAMI/training/TRAINING/training.csv,
      validate: /mnt/sdb/aditi/MAMI/trial/Users/fersiniel/Desktop/MAMI - TO LABEL/TRIAL DATASET/trial.csv,
      test: /mnt/sdb/aditi/MAMI/test/test/Test.csv,
      predict: /mnt/sdb/aditi/MAMI/test/test/Test.csv
    }
    model_class_or_path: unc-nlp/lxmert-base-uncased
    shuffle_train: True
    batch_size: 1
