# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 2
  strategy: ddp_find_unused_parameters_true
  max_epochs: 50
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/flava/harmeme
        monitor: val_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_auroc
        patience: 5
        mode: max
    - class_path: models.flava.MetricCallback
      init_args: 
        output_dict: {
          "intensity": 3,
          "target": 4
        }
model:
  class_path: models.flava.FlavaClassificationModel
  init_args:
    model_class_or_path: facebook/flava-full
    output_dict: {
      "intensity": 3,
      "target": 4
    }
data:
  class_path: datamodules.harmeme.HarMemeDataModule
  init_args:
    image_dir: /mnt/sda/mshee/datasets/fhm/img/
    annotation_filepaths: {
      train: /mnt/sda/mshee/datasets/fhm/annotations/fine_grained/train.jsonl,
      validate: /mnt/sda/mshee/datasets/fhm/annotations/fine_grained/dev_seen.jsonl,
      test: /mnt/sda/mshee/datasets/fhm/annotations/fine_grained/dev_seen.jsonl,
      predict: /mnt/sda/mshee/datasets/fhm/annotations/fine_grained/dev_seen.jsonl
    }
    model_class_or_path: facebook/flava-full
    shuffle_train: True
    dataset_type: finegrained
    labels:
    - label
    batch_size: 32
