# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  strategy: ddp_find_unused_parameters_true
  max_epochs: 50
  accumulate_grad_batches: 1
  enable_checkpointing: True
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/flava/fhm
        monitor: val_auroc
        mode: max
        save_top_k: 1
        every_n_epochs: 1
        save_last: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_auroc
        patience: 5
        mode: max
    - class_path: models.flava.MetricCallback
      init_args: 
        output_dict: {
          "labels": 2
        }
model:
  class_path: models.flava.FlavaClassificationModel
  init_args:
    model_class_or_path: facebook/flava-full
    output_dict: {
      "labels": 2
    }
data:
  class_path: datamodules.fhm.VisionLanguageDataModule
  init_args:
    image_dir: /mnt/sda/datasets/mmf/datasets/hateful_memes/defaults/images/img/
    annotation_filepaths: {
      train: /mnt/sdb/aditi/hateful_memes/hateful_memes/train.jsonl,
      validate: /mnt/sdb/aditi/hateful_memes/hateful_memes/dev_seen.jsonl,
      test: /mnt/sdb/aditi/hateful_memes/hateful_memes/dev_seen.jsonl,
      predict: /mnt/sdb/aditi/hateful_memes/hateful_memes/dev_seen.jsonl
    }
    model_class_or_path: facebook/flava-full
    shuffle_train: True
    dataset_type: finegrained
    task: hateful_cls
    batch_size: 16