# lightning.pytorch==2.0.0
seed_everything: 1111
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  accumulate_grad_batches: 1
  enable_checkpointing: True
  # callbacks: 
  #   - class_path: lightning.pytorch.callbacks.ModelCheckpoint
  #     init_args:
  #       dirpath: checkpoints/flava/harmeme
  #       monitor: val_auroc
  #       mode: max
  #       save_top_k: 1
  #       every_n_epochs: 1
  #       save_last: True
  #   - class_path: lightning.pytorch.callbacks.EarlyStopping
  #     init_args:
  #       monitor: val_auroc
  #       patience: 5
  #       mode: max
  #   - class_path: models.flava.MetricCallback
  #     init_args: 
  #       output_dict: {
  #         "intensity": 3,
  #         "target": 4
  #       }
model:
  class_path: models.flava.FlavaClassificationModel
  init_args:
    model_class_or_path: facebook/flava-full
    cls_dict: {
      "intensity": 3
    }
data:
  class_path: datamodules.VLImagesDataModule
  init_args:
    tokenizer_class_or_path: facebook/flava-full
    frcnn_class_or_path: None
    dataset_cls: FHMFGImagesDataset
    image_dir: /mnt/sda/datasets/memes/harmemes/images/
    annotation_filepaths: {
      train: /mnt/sda/datasets/memes/harmemes/annotations/train.jsonl,
      validate: /mnt/sda/datasets/memes/harmemes/annotations/val.jsonl,
      test: /mnt/sda/datasets/memes/harmemes/annotations/val.jsonl,
      predict: /mnt/sda/datasets/memes/harmemes/annotations/val.jsonl
    }
    shuffle_train: True
    labels:
    - intensity
    batch_size: 16